spring:
  application:
    name: k-coin-api

  datasource:
    url: jdbc:mysql://localhost:3306/kcoin_db
    username: kcoin
    password: kcoinpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/coin-schema.sql
      data-locations: classpath:/db/init-data.sql
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

dblock:
  lock-key: global